namespace WindowPositioner
{
    partial class FormMain
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.NotifyIcon notifyIconMain;
        private System.Windows.Forms.ContextMenuStrip contextMenuStripTray;
        private System.Windows.Forms.ToolStripMenuItem settingsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.TabControl tabControlMain;
        private System.Windows.Forms.TabPage tabPageProfiles;
        private System.Windows.Forms.TabPage tabPageSettings;
        private System.Windows.Forms.GroupBox groupBoxProfiles;
        private System.Windows.Forms.Button buttonRemoveProfile;
        private System.Windows.Forms.Button buttonAddProfile;
        private System.Windows.Forms.ListBox listBoxProfiles;
        private System.Windows.Forms.GroupBox groupBoxWindowConfigs;
        private System.Windows.Forms.DataGridView dataGridViewWindowConfigs;
        private System.Windows.Forms.Button buttonRemoveWindowConfig;
        private System.Windows.Forms.Button buttonAddWindowConfig;
        private System.Windows.Forms.CheckBox checkBoxStartWithWindows;
        private System.Windows.Forms.Button buttonSaveChanges;
        private System.Windows.Forms.Label labelActiveProfile;
        private System.Windows.Forms.ComboBox comboBoxActiveProfile;
        private System.Windows.Forms.Button buttonRenameProfile;
        private System.Windows.Forms.ToolTip toolTipGeneral;
        private System.Windows.Forms.Button buttonFetchPosition;
        private System.Windows.Forms.Button buttonFetchSize;

        protected override void Dispose(bool disposing)
        {
            if(disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormMain));
            this.notifyIconMain = new System.Windows.Forms.NotifyIcon(this.components);
            this.contextMenuStripTray = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.settingsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.tabControlMain = new System.Windows.Forms.TabControl();
            this.tabPageProfiles = new System.Windows.Forms.TabPage();
            this.groupBoxWindowConfigs = new System.Windows.Forms.GroupBox();
            this.buttonFetchSize = new System.Windows.Forms.Button();
            this.buttonFetchPosition = new System.Windows.Forms.Button();
            this.dataGridViewWindowConfigs = new System.Windows.Forms.DataGridView();
            this.buttonRemoveWindowConfig = new System.Windows.Forms.Button();
            this.buttonAddWindowConfig = new System.Windows.Forms.Button();
            this.groupBoxProfiles = new System.Windows.Forms.GroupBox();
            this.buttonRenameProfile = new System.Windows.Forms.Button();
            this.labelActiveProfile = new System.Windows.Forms.Label();
            this.comboBoxActiveProfile = new System.Windows.Forms.ComboBox();
            this.buttonRemoveProfile = new System.Windows.Forms.Button();
            this.buttonAddProfile = new System.Windows.Forms.Button();
            this.listBoxProfiles = new System.Windows.Forms.ListBox();
            this.tabPageSettings = new System.Windows.Forms.TabPage();
            this.checkBoxStartWithWindows = new System.Windows.Forms.CheckBox();
            this.buttonSaveChanges = new System.Windows.Forms.Button();
            this.toolTipGeneral = new System.Windows.Forms.ToolTip(this.components);
            this.contextMenuStripTray.SuspendLayout();
            this.tabControlMain.SuspendLayout();
            this.tabPageProfiles.SuspendLayout();
            this.groupBoxWindowConfigs.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewWindowConfigs)).BeginInit();
            this.groupBoxProfiles.SuspendLayout();
            this.tabPageSettings.SuspendLayout();
            this.SuspendLayout();
            this.notifyIconMain.ContextMenuStrip = this.contextMenuStripTray;
            this.notifyIconMain.Icon = ((System.Drawing.Icon)(resources.GetObject("notifyIconMain.Icon")));
            this.notifyIconMain.Text = "Window Positioner";
            this.notifyIconMain.Visible = true;
            this.notifyIconMain.DoubleClick += new System.EventHandler(this.notifyIconMain_DoubleClick);
            this.contextMenuStripTray.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.settingsToolStripMenuItem,
            this.exitToolStripMenuItem});
            this.contextMenuStripTray.Name = "contextMenuStripTray";
            this.contextMenuStripTray.Size = new System.Drawing.Size(117, 48);
            this.settingsToolStripMenuItem.Name = "settingsToolStripMenuItem";
            this.settingsToolStripMenuItem.Size = new System.Drawing.Size(116, 22);
            this.settingsToolStripMenuItem.Text = "&Settings";
            this.settingsToolStripMenuItem.Click += new System.EventHandler(this.settingsToolStripMenuItem_Click);
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(116, 22);
            this.exitToolStripMenuItem.Text = "&Exit";
            this.exitToolStripMenuItem.Click += new System.EventHandler(this.exitToolStripMenuItem_Click);
            this.tabControlMain.Controls.Add(this.tabPageProfiles);
            this.tabControlMain.Controls.Add(this.tabPageSettings);
            this.tabControlMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControlMain.Location = new System.Drawing.Point(0, 0);
            this.tabControlMain.Name = "tabControlMain";
            this.tabControlMain.SelectedIndex = 0;
            this.tabControlMain.Size = new System.Drawing.Size(784, 521);
            this.tabControlMain.TabIndex = 0;
            this.tabPageProfiles.Controls.Add(this.groupBoxWindowConfigs);
            this.tabPageProfiles.Controls.Add(this.groupBoxProfiles);
            this.tabPageProfiles.Location = new System.Drawing.Point(4, 24);
            this.tabPageProfiles.Name = "tabPageProfiles";
            this.tabPageProfiles.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageProfiles.Size = new System.Drawing.Size(776, 493);
            this.tabPageProfiles.TabIndex = 0;
            this.tabPageProfiles.Text = "Profiles & Windows";
            this.tabPageProfiles.UseVisualStyleBackColor = true;
            this.groupBoxWindowConfigs.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBoxWindowConfigs.Controls.Add(this.buttonFetchSize);
            this.groupBoxWindowConfigs.Controls.Add(this.buttonFetchPosition);
            this.groupBoxWindowConfigs.Controls.Add(this.dataGridViewWindowConfigs);
            this.groupBoxWindowConfigs.Controls.Add(this.buttonRemoveWindowConfig);
            this.groupBoxWindowConfigs.Controls.Add(this.buttonAddWindowConfig);
            this.groupBoxWindowConfigs.Location = new System.Drawing.Point(200, 7);
            this.groupBoxWindowConfigs.Name = "groupBoxWindowConfigs";
            this.groupBoxWindowConfigs.Size = new System.Drawing.Size(570, 480);
            this.groupBoxWindowConfigs.TabIndex = 1;
            this.groupBoxWindowConfigs.TabStop = false;
            this.groupBoxWindowConfigs.Text = "Window Configurations for Selected Profile";
            this.buttonFetchSize.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonFetchSize.Enabled = false;
            this.buttonFetchSize.Location = new System.Drawing.Point(464, 445);
            this.buttonFetchSize.Name = "buttonFetchSize";
            this.buttonFetchSize.Size = new System.Drawing.Size(100, 25);
            this.buttonFetchSize.TabIndex = 4;
            this.buttonFetchSize.Text = "Fetch Size";
            this.toolTipGeneral.SetToolTip(this.buttonFetchSize, "Update Width,Height from the live window matching this configuration");
            this.buttonFetchSize.UseVisualStyleBackColor = true;
            this.buttonFetchSize.Click += new System.EventHandler(this.buttonFetchSize_Click);
            this.buttonFetchPosition.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonFetchPosition.Enabled = false;
            this.buttonFetchPosition.Location = new System.Drawing.Point(358, 445);
            this.buttonFetchPosition.Name = "buttonFetchPosition";
            this.buttonFetchPosition.Size = new System.Drawing.Size(100, 25);
            this.buttonFetchPosition.TabIndex = 3;
            this.buttonFetchPosition.Text = "Fetch Position";
            this.toolTipGeneral.SetToolTip(this.buttonFetchPosition, "Update X,Y from the live window matching this configuration");
            this.buttonFetchPosition.UseVisualStyleBackColor = true;
            this.buttonFetchPosition.Click += new System.EventHandler(this.buttonFetchPosition_Click);
            this.dataGridViewWindowConfigs.AllowUserToAddRows = false;
            this.dataGridViewWindowConfigs.AllowUserToDeleteRows = false;
            this.dataGridViewWindowConfigs.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dataGridViewWindowConfigs.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dataGridViewWindowConfigs.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridViewWindowConfigs.Location = new System.Drawing.Point(7, 23);
            this.dataGridViewWindowConfigs.MultiSelect = false;
            this.dataGridViewWindowConfigs.Name = "dataGridViewWindowConfigs";
            this.dataGridViewWindowConfigs.RowTemplate.Height = 25;
            this.dataGridViewWindowConfigs.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataGridViewWindowConfigs.Size = new System.Drawing.Size(557, 412);
            this.dataGridViewWindowConfigs.TabIndex = 0;
            this.dataGridViewWindowConfigs.CellEndEdit += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataGridViewWindowConfigs_CellEndEdit);
            this.dataGridViewWindowConfigs.SelectionChanged += new System.EventHandler(this.dataGridViewWindowConfigs_SelectionChanged);
            this.buttonRemoveWindowConfig.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.buttonRemoveWindowConfig.Enabled = false;
            this.buttonRemoveWindowConfig.Location = new System.Drawing.Point(88, 445);
            this.buttonRemoveWindowConfig.Name = "buttonRemoveWindowConfig";
            this.buttonRemoveWindowConfig.Size = new System.Drawing.Size(75, 25);
            this.buttonRemoveWindowConfig.TabIndex = 2;
            this.buttonRemoveWindowConfig.Text = "Remove";
            this.buttonRemoveWindowConfig.UseVisualStyleBackColor = true;
            this.buttonRemoveWindowConfig.Click += new System.EventHandler(this.buttonRemoveWindowConfig_Click);
            this.buttonAddWindowConfig.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.buttonAddWindowConfig.Location = new System.Drawing.Point(7, 445);
            this.buttonAddWindowConfig.Name = "buttonAddWindowConfig";
            this.buttonAddWindowConfig.Size = new System.Drawing.Size(75, 25);
            this.buttonAddWindowConfig.TabIndex = 1;
            this.buttonAddWindowConfig.Text = "Add New";
            this.toolTipGeneral.SetToolTip(this.buttonAddWindowConfig, "Add a new window configuration by selecting a running process");
            this.buttonAddWindowConfig.UseVisualStyleBackColor = true;
            this.buttonAddWindowConfig.Click += new System.EventHandler(this.buttonAddWindowConfig_Click);
            this.groupBoxProfiles.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBoxProfiles.Controls.Add(this.buttonRenameProfile);
            this.groupBoxProfiles.Controls.Add(this.labelActiveProfile);
            this.groupBoxProfiles.Controls.Add(this.comboBoxActiveProfile);
            this.groupBoxProfiles.Controls.Add(this.buttonRemoveProfile);
            this.groupBoxProfiles.Controls.Add(this.buttonAddProfile);
            this.groupBoxProfiles.Controls.Add(this.listBoxProfiles);
            this.groupBoxProfiles.Location = new System.Drawing.Point(7, 7);
            this.groupBoxProfiles.Name = "groupBoxProfiles";
            this.groupBoxProfiles.Size = new System.Drawing.Size(187, 480);
            this.groupBoxProfiles.TabIndex = 0;
            this.groupBoxProfiles.TabStop = false;
            this.groupBoxProfiles.Text = "Profiles";
            this.buttonRenameProfile.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.buttonRenameProfile.Location = new System.Drawing.Point(7, 414);
            this.buttonRenameProfile.Name = "buttonRenameProfile";
            this.buttonRenameProfile.Size = new System.Drawing.Size(174, 25);
            this.buttonRenameProfile.TabIndex = 5;
            this.buttonRenameProfile.Text = "Rename Selected";
            this.buttonRenameProfile.UseVisualStyleBackColor = true;
            this.buttonRenameProfile.Click += new System.EventHandler(this.buttonRenameProfile_Click);
            this.labelActiveProfile.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.labelActiveProfile.AutoSize = true;
            this.labelActiveProfile.Location = new System.Drawing.Point(7, 355);
            this.labelActiveProfile.Name = "labelActiveProfile";
            this.labelActiveProfile.Size = new System.Drawing.Size(78, 15);
            this.labelActiveProfile.TabIndex = 4;
            this.labelActiveProfile.Text = "Active Profile:";
            this.comboBoxActiveProfile.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.comboBoxActiveProfile.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxActiveProfile.FormattingEnabled = true;
            this.comboBoxActiveProfile.Location = new System.Drawing.Point(7, 373);
            this.comboBoxActiveProfile.Name = "comboBoxActiveProfile";
            this.comboBoxActiveProfile.Size = new System.Drawing.Size(174, 23);
            this.comboBoxActiveProfile.TabIndex = 3;
            this.comboBoxActiveProfile.SelectedIndexChanged += new System.EventHandler(this.comboBoxActiveProfile_SelectedIndexChanged);
            this.buttonRemoveProfile.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.buttonRemoveProfile.Location = new System.Drawing.Point(98, 445);
            this.buttonRemoveProfile.Name = "buttonRemoveProfile";
            this.buttonRemoveProfile.Size = new System.Drawing.Size(83, 25);
            this.buttonRemoveProfile.TabIndex = 2;
            this.buttonRemoveProfile.Text = "Remove";
            this.buttonRemoveProfile.UseVisualStyleBackColor = true;
            this.buttonRemoveProfile.Click += new System.EventHandler(this.buttonRemoveProfile_Click);
            this.buttonAddProfile.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.buttonAddProfile.Location = new System.Drawing.Point(7, 445);
            this.buttonAddProfile.Name = "buttonAddProfile";
            this.buttonAddProfile.Size = new System.Drawing.Size(83, 25);
            this.buttonAddProfile.TabIndex = 1;
            this.buttonAddProfile.Text = "Add New";
            this.buttonAddProfile.UseVisualStyleBackColor = true;
            this.buttonAddProfile.Click += new System.EventHandler(this.buttonAddProfile_Click);
            this.listBoxProfiles.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.listBoxProfiles.FormattingEnabled = true;
            this.listBoxProfiles.ItemHeight = 15;
            this.listBoxProfiles.Location = new System.Drawing.Point(7, 23);
            this.listBoxProfiles.Name = "listBoxProfiles";
            this.listBoxProfiles.Size = new System.Drawing.Size(174, 319);
            this.listBoxProfiles.TabIndex = 0;
            this.listBoxProfiles.SelectedIndexChanged += new System.EventHandler(this.listBoxProfiles_SelectedIndexChanged);
            this.tabPageSettings.Controls.Add(this.checkBoxStartWithWindows);
            this.tabPageSettings.Location = new System.Drawing.Point(4, 24);
            this.tabPageSettings.Name = "tabPageSettings";
            this.tabPageSettings.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageSettings.Size = new System.Drawing.Size(776, 493);
            this.tabPageSettings.TabIndex = 1;
            this.tabPageSettings.Text = "Application Settings";
            this.tabPageSettings.UseVisualStyleBackColor = true;
            this.checkBoxStartWithWindows.AutoSize = true;
            this.checkBoxStartWithWindows.Location = new System.Drawing.Point(15, 15);
            this.checkBoxStartWithWindows.Name = "checkBoxStartWithWindows";
            this.checkBoxStartWithWindows.Size = new System.Drawing.Size(127, 19);
            this.checkBoxStartWithWindows.TabIndex = 0;
            this.checkBoxStartWithWindows.Text = "Start with Windows";
            this.checkBoxStartWithWindows.UseVisualStyleBackColor = true;
            this.checkBoxStartWithWindows.CheckedChanged += new System.EventHandler(this.checkBoxStartWithWindows_CheckedChanged);
            this.buttonSaveChanges.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.buttonSaveChanges.Location = new System.Drawing.Point(0, 521);
            this.buttonSaveChanges.Name = "buttonSaveChanges";
            this.buttonSaveChanges.Size = new System.Drawing.Size(784, 40);
            this.buttonSaveChanges.TabIndex = 1;
            this.buttonSaveChanges.Text = "Save All Changes";
            this.buttonSaveChanges.UseVisualStyleBackColor = true;
            this.buttonSaveChanges.Click += new System.EventHandler(this.buttonSaveChanges_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 561);
            this.Controls.Add(this.tabControlMain);
            this.Controls.Add(this.buttonSaveChanges);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(600, 400);
            this.Name = "FormMain";
            this.Text = "Window Positioner Settings";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.FormMain_FormClosing);
            this.Load += new System.EventHandler(this.FormMain_Load);
            this.Shown += new System.EventHandler(this.FormMain_Shown);
            this.contextMenuStripTray.ResumeLayout(false);
            this.tabControlMain.ResumeLayout(false);
            this.tabPageProfiles.ResumeLayout(false);
            this.groupBoxWindowConfigs.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewWindowConfigs)).EndInit();
            this.groupBoxProfiles.ResumeLayout(false);
            this.groupBoxProfiles.PerformLayout();
            this.tabPageSettings.ResumeLayout(false);
            this.tabPageSettings.PerformLayout();
            this.ResumeLayout(false);

        }
    }
}