namespace WindowPlacementManager
{
    partial class FormMain
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.NotifyIcon notifyIconMain;
        private System.Windows.Forms.ContextMenuStrip contextMenuStripTray;
        private System.Windows.Forms.ToolStripMenuItem settingsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.TabControl tabControlMain;
        private System.Windows.Forms.TabPage tabPageProfiles;
        private System.Windows.Forms.TabPage tabPageSettings;
        private System.Windows.Forms.GroupBox groupBoxProfiles;
        private System.Windows.Forms.Button buttonRemoveProfile;
        private System.Windows.Forms.Button buttonAddProfile;
        private System.Windows.Forms.GroupBox groupBoxWindowConfigs;
        private System.Windows.Forms.DataGridView dataGridViewWindowConfigs;
        private System.Windows.Forms.Button buttonRemoveWindowConfig;
        private System.Windows.Forms.Button buttonAddWindowConfig;
        private System.Windows.Forms.Button buttonSaveChanges;
        private System.Windows.Forms.Label labelActiveProfile;
        private System.Windows.Forms.ComboBox comboBoxActiveProfile;
        private System.Windows.Forms.Button buttonRenameProfile;
        private System.Windows.Forms.ToolTip toolTipGeneral;
        private System.Windows.Forms.Button buttonFetchPosition;
        private System.Windows.Forms.Button buttonFetchSize;
        private System.Windows.Forms.Button buttonCloneProfile;
        private System.Windows.Forms.Button buttonTestSelectedProfile;
        private System.Windows.Forms.Label labelStartupOptions;
        private System.Windows.Forms.ComboBox comboBoxStartupOptions;
        private System.Windows.Forms.LinkLabel linkLabelGitHub;
        private System.Windows.Forms.Label labelCredits;
        private System.Windows.Forms.CheckBox checkBoxDisableProgram;

        private System.Windows.Forms.Button buttonActivateLaunchApp;
        private System.Windows.Forms.Button buttonLaunchAllProfileApps;
        private System.Windows.Forms.Button buttonFocusAllProfileApps;


        protected override void Dispose(bool disposing)
        {
            if(disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.notifyIconMain = new System.Windows.Forms.NotifyIcon(this.components);
            this.contextMenuStripTray = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.settingsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.tabControlMain = new System.Windows.Forms.TabControl();
            this.tabPageProfiles = new System.Windows.Forms.TabPage();
            this.checkBoxDisableProgram = new System.Windows.Forms.CheckBox();
            this.groupBoxWindowConfigs = new System.Windows.Forms.GroupBox();
            this.buttonLaunchAllProfileApps = new System.Windows.Forms.Button();
            this.buttonFocusAllProfileApps = new System.Windows.Forms.Button();
            this.buttonTestSelectedProfile = new System.Windows.Forms.Button();
            this.buttonAddWindowConfig = new System.Windows.Forms.Button();
            this.buttonRemoveWindowConfig = new System.Windows.Forms.Button();
            this.buttonActivateLaunchApp = new System.Windows.Forms.Button();
            this.buttonFetchPosition = new System.Windows.Forms.Button();
            this.buttonFetchSize = new System.Windows.Forms.Button();
            this.dataGridViewWindowConfigs = new System.Windows.Forms.DataGridView();
            this.groupBoxProfiles = new System.Windows.Forms.GroupBox();
            this.labelActiveProfile = new System.Windows.Forms.Label();
            this.comboBoxActiveProfile = new System.Windows.Forms.ComboBox();
            this.buttonAddProfile = new System.Windows.Forms.Button();
            this.buttonRenameProfile = new System.Windows.Forms.Button();
            this.buttonCloneProfile = new System.Windows.Forms.Button();
            this.buttonRemoveProfile = new System.Windows.Forms.Button();
            this.tabPageSettings = new System.Windows.Forms.TabPage();
            this.linkLabelGitHub = new System.Windows.Forms.LinkLabel();
            this.labelCredits = new System.Windows.Forms.Label();
            this.comboBoxStartupOptions = new System.Windows.Forms.ComboBox();
            this.labelStartupOptions = new System.Windows.Forms.Label();
            this.buttonSaveChanges = new System.Windows.Forms.Button();
            this.toolTipGeneral = new System.Windows.Forms.ToolTip(this.components);
            this.contextMenuStripTray.SuspendLayout();
            this.tabControlMain.SuspendLayout();
            this.tabPageProfiles.SuspendLayout();
            this.groupBoxWindowConfigs.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewWindowConfigs)).BeginInit();
            this.groupBoxProfiles.SuspendLayout();
            this.tabPageSettings.SuspendLayout();
            this.SuspendLayout();
            this.notifyIconMain.ContextMenuStrip = this.contextMenuStripTray;
            this.notifyIconMain.Text = "Window Positioner";
            this.notifyIconMain.Visible = true;
            this.notifyIconMain.DoubleClick += new System.EventHandler(this.notifyIconMain_DoubleClick);
            this.contextMenuStripTray.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.settingsToolStripMenuItem,
            this.exitToolStripMenuItem});
            this.contextMenuStripTray.Name = "contextMenuStripTray";
            this.contextMenuStripTray.Size = new System.Drawing.Size(117, 48);
            this.settingsToolStripMenuItem.Name = "settingsToolStripMenuItem";
            this.settingsToolStripMenuItem.Size = new System.Drawing.Size(116, 22);
            this.settingsToolStripMenuItem.Text = "&Settings";
            this.settingsToolStripMenuItem.Click += new System.EventHandler(this.settingsToolStripMenuItem_Click);
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(116, 22);
            this.exitToolStripMenuItem.Text = "&Exit";
            this.exitToolStripMenuItem.Click += new System.EventHandler(this.exitToolStripMenuItem_Click);
            this.tabControlMain.Controls.Add(this.tabPageProfiles);
            this.tabControlMain.Controls.Add(this.tabPageSettings);
            this.tabControlMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControlMain.Location = new System.Drawing.Point(0, 0);
            this.tabControlMain.Name = "tabControlMain";
            this.tabControlMain.SelectedIndex = 0;
            this.tabControlMain.Size = new System.Drawing.Size(784, 521);
            this.tabControlMain.TabIndex = 0;
            this.tabPageProfiles.Controls.Add(this.checkBoxDisableProgram);
            this.tabPageProfiles.Controls.Add(this.groupBoxWindowConfigs);
            this.tabPageProfiles.Controls.Add(this.groupBoxProfiles);
            this.tabPageProfiles.Location = new System.Drawing.Point(4, 24);
            this.tabPageProfiles.Name = "tabPageProfiles";
            this.tabPageProfiles.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageProfiles.Size = new System.Drawing.Size(776, 493);
            this.tabPageProfiles.TabIndex = 0;
            this.tabPageProfiles.Text = "Profiles & Windows";
            this.tabPageProfiles.UseVisualStyleBackColor = true;
            this.checkBoxDisableProgram.AutoSize = true;
            this.checkBoxDisableProgram.Location = new System.Drawing.Point(573, 7);
            this.checkBoxDisableProgram.Name = "checkBoxDisableProgram";
            this.checkBoxDisableProgram.Size = new System.Drawing.Size(195, 19);
            this.checkBoxDisableProgram.TabIndex = 2;
            this.toolTipGeneral.SetToolTip(this.checkBoxDisableProgram, "If this checkbox is enabled, the program will not adjust any windows.");
            this.checkBoxDisableProgram.UseVisualStyleBackColor = true;
            this.checkBoxDisableProgram.CheckedChanged += new System.EventHandler(this.checkBoxDisableProgram_CheckedChanged);
            this.groupBoxWindowConfigs.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBoxWindowConfigs.Controls.Add(this.buttonLaunchAllProfileApps);
            this.groupBoxWindowConfigs.Controls.Add(this.buttonFocusAllProfileApps);
            this.groupBoxWindowConfigs.Controls.Add(this.buttonTestSelectedProfile);
            this.groupBoxWindowConfigs.Controls.Add(this.buttonAddWindowConfig);
            this.groupBoxWindowConfigs.Controls.Add(this.buttonRemoveWindowConfig);
            this.groupBoxWindowConfigs.Controls.Add(this.buttonActivateLaunchApp);
            this.groupBoxWindowConfigs.Controls.Add(this.buttonFetchPosition);
            this.groupBoxWindowConfigs.Controls.Add(this.buttonFetchSize);
            this.groupBoxWindowConfigs.Controls.Add(this.dataGridViewWindowConfigs);
            this.groupBoxWindowConfigs.Location = new System.Drawing.Point(200, 30);
            this.groupBoxWindowConfigs.Name = "groupBoxWindowConfigs";
            this.groupBoxWindowConfigs.Size = new System.Drawing.Size(570, 457);
            this.groupBoxWindowConfigs.TabIndex = 1;
            this.groupBoxWindowConfigs.TabStop = false;
            this.groupBoxWindowConfigs.Text = "Window Configurations for Selected Profile";
            this.buttonLaunchAllProfileApps.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonLaunchAllProfileApps.Enabled = false;
            this.buttonLaunchAllProfileApps.Location = new System.Drawing.Point(250, 390);
            this.buttonLaunchAllProfileApps.Name = "buttonLaunchAllProfileApps";
            this.buttonLaunchAllProfileApps.Size = new System.Drawing.Size(100, 25);
            this.buttonLaunchAllProfileApps.TabIndex = 1;
            this.buttonLaunchAllProfileApps.Text = "Launch All";
            this.toolTipGeneral.SetToolTip(this.buttonLaunchAllProfileApps, "Launch all configured apps in this profile that are not currently running.");
            this.buttonLaunchAllProfileApps.UseVisualStyleBackColor = true;
            this.buttonLaunchAllProfileApps.Click += new System.EventHandler(this.buttonLaunchAllProfileApps_Click);
            this.buttonFocusAllProfileApps.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonFocusAllProfileApps.Enabled = false;
            this.buttonFocusAllProfileApps.Location = new System.Drawing.Point(357, 390);
            this.buttonFocusAllProfileApps.Name = "buttonFocusAllProfileApps";
            this.buttonFocusAllProfileApps.Size = new System.Drawing.Size(100, 25);
            this.buttonFocusAllProfileApps.TabIndex = 2;
            this.buttonFocusAllProfileApps.Text = "Focus All";
            this.toolTipGeneral.SetToolTip(this.buttonFocusAllProfileApps, "Bring all running configured apps in this profile to the foreground.");
            this.buttonFocusAllProfileApps.UseVisualStyleBackColor = true;
            this.buttonFocusAllProfileApps.Click += new System.EventHandler(this.buttonFocusAllProfileApps_Click);
            this.buttonTestSelectedProfile.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonTestSelectedProfile.Enabled = false;
            this.buttonTestSelectedProfile.Location = new System.Drawing.Point(464, 390);
            this.buttonTestSelectedProfile.Name = "buttonTestSelectedProfile";
            this.buttonTestSelectedProfile.Size = new System.Drawing.Size(100, 25);
            this.buttonTestSelectedProfile.TabIndex = 3;
            this.buttonTestSelectedProfile.Text = "Test Layout";
            this.toolTipGeneral.SetToolTip(this.buttonTestSelectedProfile, "Apply window positions/sizes for the currently selected profile.");
            this.buttonTestSelectedProfile.UseVisualStyleBackColor = true;
            this.buttonTestSelectedProfile.Click += new System.EventHandler(this.buttonTestSelectedProfile_Click);
            this.buttonAddWindowConfig.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.buttonAddWindowConfig.Location = new System.Drawing.Point(7, 422);
            this.buttonAddWindowConfig.Name = "buttonAddWindowConfig";
            this.buttonAddWindowConfig.Size = new System.Drawing.Size(115, 25);
            this.buttonAddWindowConfig.TabIndex = 4;
            this.buttonAddWindowConfig.Text = "Add Window";
            this.toolTipGeneral.SetToolTip(this.buttonAddWindowConfig, "Add a new window configuration by selecting a running process");
            this.buttonAddWindowConfig.UseVisualStyleBackColor = true;
            this.buttonAddWindowConfig.Click += new System.EventHandler(this.buttonAddWindowConfig_Click);
            this.buttonRemoveWindowConfig.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.buttonRemoveWindowConfig.Enabled = false;
            this.buttonRemoveWindowConfig.Location = new System.Drawing.Point(129, 422);
            this.buttonRemoveWindowConfig.Name = "buttonRemoveWindowConfig";
            this.buttonRemoveWindowConfig.Size = new System.Drawing.Size(115, 25);
            this.buttonRemoveWindowConfig.TabIndex = 5;
            this.buttonRemoveWindowConfig.Text = "Remove Window";
            this.buttonRemoveWindowConfig.UseVisualStyleBackColor = true;
            this.buttonRemoveWindowConfig.Click += new System.EventHandler(this.buttonRemoveWindowConfig_Click);
            this.buttonActivateLaunchApp.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.buttonActivateLaunchApp.Enabled = false;
            this.buttonActivateLaunchApp.Location = new System.Drawing.Point(251, 422);
            this.buttonActivateLaunchApp.Name = "buttonActivateLaunchApp";
            this.buttonActivateLaunchApp.Size = new System.Drawing.Size(100, 25);
            this.buttonActivateLaunchApp.TabIndex = 6;
            this.buttonActivateLaunchApp.Text = "Activate Sel.";
            this.toolTipGeneral.SetToolTip(this.buttonActivateLaunchApp, "Launch the selected app if not running, or bring its window to the foreground.");
            this.buttonActivateLaunchApp.UseVisualStyleBackColor = true;
            this.buttonActivateLaunchApp.Click += new System.EventHandler(this.buttonActivateLaunchApp_Click);
            this.buttonFetchPosition.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonFetchPosition.Enabled = false;
            this.buttonFetchPosition.Location = new System.Drawing.Point(357, 422);
            this.buttonFetchPosition.Name = "buttonFetchPosition";
            this.buttonFetchPosition.Size = new System.Drawing.Size(100, 25);
            this.buttonFetchPosition.TabIndex = 7;
            this.buttonFetchPosition.Text = "Fetch Position";
            this.toolTipGeneral.SetToolTip(this.buttonFetchPosition, "Update X,Y from the live window matching this configuration");
            this.buttonFetchPosition.UseVisualStyleBackColor = true;
            this.buttonFetchPosition.Click += new System.EventHandler(this.buttonFetchPosition_Click);
            this.buttonFetchSize.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonFetchSize.Enabled = false;
            this.buttonFetchSize.Location = new System.Drawing.Point(464, 422);
            this.buttonFetchSize.Name = "buttonFetchSize";
            this.buttonFetchSize.Size = new System.Drawing.Size(100, 25);
            this.buttonFetchSize.TabIndex = 8;
            this.buttonFetchSize.Text = "Fetch Size";
            this.toolTipGeneral.SetToolTip(this.buttonFetchSize, "Update Width,Height from the live window matching this configuration");
            this.buttonFetchSize.UseVisualStyleBackColor = true;
            this.buttonFetchSize.Click += new System.EventHandler(this.buttonFetchSize_Click);
            this.dataGridViewWindowConfigs.AllowUserToAddRows = false;
            this.dataGridViewWindowConfigs.AllowUserToDeleteRows = false;
            this.dataGridViewWindowConfigs.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dataGridViewWindowConfigs.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dataGridViewWindowConfigs.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridViewWindowConfigs.Location = new System.Drawing.Point(7, 23);
            this.dataGridViewWindowConfigs.MultiSelect = false;
            this.dataGridViewWindowConfigs.Name = "dataGridViewWindowConfigs";
            this.dataGridViewWindowConfigs.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataGridViewWindowConfigs.Size = new System.Drawing.Size(557, 360);
            this.dataGridViewWindowConfigs.TabIndex = 0;
            this.dataGridViewWindowConfigs.CellEndEdit += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataGridViewWindowConfigs_CellEndEdit);
            this.dataGridViewWindowConfigs.SelectionChanged += new System.EventHandler(this.dataGridViewWindowConfigs_SelectionChanged);
            this.groupBoxProfiles.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBoxProfiles.Controls.Add(this.labelActiveProfile);
            this.groupBoxProfiles.Controls.Add(this.comboBoxActiveProfile);
            this.groupBoxProfiles.Controls.Add(this.buttonAddProfile);
            this.groupBoxProfiles.Controls.Add(this.buttonRenameProfile);
            this.groupBoxProfiles.Controls.Add(this.buttonCloneProfile);
            this.groupBoxProfiles.Controls.Add(this.buttonRemoveProfile);
            this.groupBoxProfiles.Location = new System.Drawing.Point(7, 7);
            this.groupBoxProfiles.Name = "groupBoxProfiles";
            this.groupBoxProfiles.Size = new System.Drawing.Size(187, 480);
            this.groupBoxProfiles.TabIndex = 0;
            this.groupBoxProfiles.TabStop = false;
            this.groupBoxProfiles.Text = "Profile Editor";
            this.labelActiveProfile.AutoSize = true;
            this.labelActiveProfile.Location = new System.Drawing.Point(7, 20);
            this.labelActiveProfile.Name = "labelActiveProfile";
            this.labelActiveProfile.Size = new System.Drawing.Size(80, 15);
            this.labelActiveProfile.TabIndex = 0;
            this.labelActiveProfile.Text = "Active Profile:";
            this.comboBoxActiveProfile.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.comboBoxActiveProfile.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxActiveProfile.FormattingEnabled = true;
            this.comboBoxActiveProfile.Location = new System.Drawing.Point(7, 38);
            this.comboBoxActiveProfile.Name = "comboBoxActiveProfile";
            this.comboBoxActiveProfile.Size = new System.Drawing.Size(174, 23);
            this.comboBoxActiveProfile.TabIndex = 1;
            this.comboBoxActiveProfile.SelectedIndexChanged += new System.EventHandler(this.comboBoxActiveProfile_SelectedIndexChanged);
            this.buttonAddProfile.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonAddProfile.Location = new System.Drawing.Point(7, 70);
            this.buttonAddProfile.Name = "buttonAddProfile";
            this.buttonAddProfile.Size = new System.Drawing.Size(174, 25);
            this.buttonAddProfile.TabIndex = 2;
            this.buttonAddProfile.Text = "Add New Profile";
            this.buttonAddProfile.UseVisualStyleBackColor = true;
            this.buttonAddProfile.Click += new System.EventHandler(this.buttonAddProfile_Click);
            this.buttonRenameProfile.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonRenameProfile.Location = new System.Drawing.Point(7, 101);
            this.buttonRenameProfile.Name = "buttonRenameProfile";
            this.buttonRenameProfile.Size = new System.Drawing.Size(174, 25);
            this.buttonRenameProfile.TabIndex = 3;
            this.buttonRenameProfile.Text = "Rename Selected";
            this.buttonRenameProfile.UseVisualStyleBackColor = true;
            this.buttonRenameProfile.Click += new System.EventHandler(this.buttonRenameProfile_Click);
            this.buttonCloneProfile.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonCloneProfile.Location = new System.Drawing.Point(7, 132);
            this.buttonCloneProfile.Name = "buttonCloneProfile";
            this.buttonCloneProfile.Size = new System.Drawing.Size(174, 25);
            this.buttonCloneProfile.TabIndex = 4;
            this.buttonCloneProfile.Text = "Clone Selected";
            this.buttonCloneProfile.UseVisualStyleBackColor = true;
            this.buttonCloneProfile.Click += new System.EventHandler(this.buttonCloneProfile_Click);
            this.buttonRemoveProfile.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonRemoveProfile.Location = new System.Drawing.Point(7, 163);
            this.buttonRemoveProfile.Name = "buttonRemoveProfile";
            this.buttonRemoveProfile.Size = new System.Drawing.Size(174, 25);
            this.buttonRemoveProfile.TabIndex = 5;
            this.buttonRemoveProfile.Text = "Remove Selected";
            this.buttonRemoveProfile.UseVisualStyleBackColor = true;
            this.buttonRemoveProfile.Click += new System.EventHandler(this.buttonRemoveProfile_Click);
            this.tabPageSettings.Controls.Add(this.linkLabelGitHub);
            this.tabPageSettings.Controls.Add(this.labelCredits);
            this.tabPageSettings.Controls.Add(this.comboBoxStartupOptions);
            this.tabPageSettings.Controls.Add(this.labelStartupOptions);
            this.tabPageSettings.Location = new System.Drawing.Point(4, 24);
            this.tabPageSettings.Name = "tabPageSettings";
            this.tabPageSettings.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageSettings.Size = new System.Drawing.Size(776, 493);
            this.tabPageSettings.TabIndex = 1;
            this.tabPageSettings.Text = "Application Settings";
            this.tabPageSettings.UseVisualStyleBackColor = true;
            this.linkLabelGitHub.AutoSize = true;
            this.linkLabelGitHub.Location = new System.Drawing.Point(15, 80);
            this.linkLabelGitHub.Name = "linkLabelGitHub";
            this.linkLabelGitHub.Size = new System.Drawing.Size(119, 15);
            this.linkLabelGitHub.TabIndex = 3;
            this.linkLabelGitHub.TabStop = true;
            this.linkLabelGitHub.Text = "Visit my GitHub page";
            this.linkLabelGitHub.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.linkLabelGitHub_LinkClicked);
            this.labelCredits.AutoSize = true;
            this.labelCredits.Location = new System.Drawing.Point(15, 60);
            this.labelCredits.Name = "labelCredits";
            this.labelCredits.Size = new System.Drawing.Size(174, 15);
            this.labelCredits.TabIndex = 2;
            this.labelCredits.Text = "Found an issue or have an idea?";
            this.comboBoxStartupOptions.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxStartupOptions.FormattingEnabled = true;
            this.comboBoxStartupOptions.Location = new System.Drawing.Point(220, 17);
            this.comboBoxStartupOptions.Name = "comboBoxStartupOptions";
            this.comboBoxStartupOptions.Size = new System.Drawing.Size(250, 23);
            this.comboBoxStartupOptions.TabIndex = 1;
            this.labelStartupOptions.AutoSize = true;
            this.labelStartupOptions.Location = new System.Drawing.Point(15, 20);
            this.labelStartupOptions.Name = "labelStartupOptions";
            this.labelStartupOptions.Size = new System.Drawing.Size(93, 15);
            this.labelStartupOptions.TabIndex = 0;
            this.labelStartupOptions.Text = "Startup Options:";
            this.buttonSaveChanges.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.buttonSaveChanges.Location = new System.Drawing.Point(0, 521);
            this.buttonSaveChanges.Name = "buttonSaveChanges";
            this.buttonSaveChanges.Size = new System.Drawing.Size(784, 40);
            this.buttonSaveChanges.TabIndex = 1;
            this.buttonSaveChanges.Text = "Save All Changes";
            this.buttonSaveChanges.UseVisualStyleBackColor = true;
            this.buttonSaveChanges.Click += new System.EventHandler(this.buttonSaveChanges_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 561);
            this.Controls.Add(this.tabControlMain);
            this.Controls.Add(this.buttonSaveChanges);
            this.MinimumSize = new System.Drawing.Size(600, 400);
            this.Name = "FormMain";
            this.Text = "Window Placement Manager";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.FormMain_FormClosing);
            this.Load += new System.EventHandler(this.FormMain_Load);
            this.Shown += new System.EventHandler(this.FormMain_Shown);
            this.contextMenuStripTray.ResumeLayout(false);
            this.tabControlMain.ResumeLayout(false);
            this.tabPageProfiles.ResumeLayout(false);
            this.tabPageProfiles.PerformLayout();
            this.groupBoxWindowConfigs.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewWindowConfigs)).EndInit();
            this.groupBoxProfiles.ResumeLayout(false);
            this.groupBoxProfiles.PerformLayout();
            this.tabPageSettings.ResumeLayout(false);
            this.tabPageSettings.PerformLayout();
            this.ResumeLayout(false);
        }
    }
}